version: '3.8'
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.12.11-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=john
      - RABBITMQ_DEFAULT_PASS=qweqwe
    ports:
      # rabbitmq server
      - "5672:5672"
      # Web interface
      - "15672:15672"
  selenium:
    container_name: "selenium"
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: "2g"
